package com.paridhi.resume_screener.service;

import com.paridhi.resume_screener.dto.AIScreeningResponse;
import com.paridhi.resume_screener.dto.ScreeningResponse;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@Service
public class ResultFileService {

    public String generateKeywordResultFile(ScreeningResponse response) {
        return """
                ============================================
                RESUME SCREENING REPORT (Keyword Analysis)
                ============================================
                Generated: %s
                
                OVERALL SCORE: %d/100
                
                RECOMMENDATION: %s
                
                FEEDBACK:
                %s
                
                MATCHED SKILLS:
                %s
                
                MISSING SKILLS:
                %s
                ============================================
                Generated by Resume Screener API
                """.formatted(
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss")),
                response.getOverallScore(),
                response.getRecommendation(),
                response.getFeedback(),
                response.getMatchedSkills().isEmpty() ? "None" : response.getMatchedSkills(),
                response.getMissingSkills().isEmpty() ? "None" : response.getMissingSkills()
        );
    }

    public String generateAIResultFile(AIScreeningResponse response) {
        return """
                ============================================
                RESUME SCREENING REPORT (AI Analysis)
                ============================================
                Generated: %s
                
                OVERALL SCORE: %d/100
                
                RECOMMENDATION: %s
                
                FEEDBACK:
                %s
                
                MATCHED SKILLS:
                %s
                
                MISSING SKILLS:
                %s
                
                EXPERIENCE MATCH:
                %s
                
                INTERVIEW PREPARATION TIPS:
                %s
                ============================================
                Powered by Google Gemini LLM
                Generated by Resume Screener API
                """.formatted(
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss")),
                response.getOverallScore(),
                response.getRecommendation(),
                response.getFeedback(),
                response.getMatchedSkills(),
                response.getMissingSkills(),
                response.getExperienceMatch(),
                response.getInterviewTips()
        );
    }
}